# Generated by Django 3.1.7 on 2021-03-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(default='', max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=500)),
                ('date_published', models.DateTimeField(default=None, null=True)),
                ('article_text', models.CharField(default='', max_length=3000)),
                ('url', models.CharField(default='', max_length=100)),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.tag')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
